### ISSUE TITLE
It is worth considering that curve may turn out to be, for example, a vector network

### ISSUE THREAD

**Issue by Andreslav** [codelastnight/to-path-figma#17]
Now the plugin just does nothing, although a warning is worth it.

**Comment by codelastnight** [comment]
true, I'll put in a warning for now. Maybe in the future I can add support but its not a priority for now

**Comment by codelastnight** [comment]
actually, in the near future I am probably going to switch from using the vectorPath.data value and instead use the vectorNetwork data, theres multiple issues linked to the fact that I used vectorPath.data instead of vectorNetworks (such as the fact that the plugin cant deal with the curve being rotated, or flipped horizontally/vertically) so this might be implemented when I do the switch then.

**Comment by codelastnight** [comment]
added warning in 1.2.1
